apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: minio
  labels:
     app: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: minio-svc
  replicas: 3
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        env:
        - name: MINIO_SERVER_URL
          value: "http://10.39.153.18:9090"
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        image: minio/minio:latest
        args:
        - server
        - http://minio-0.minio-svc.default.svc.cluster.local/mnt/disk1
        - http://minio-1.minio-svc.default.svc.cluster.local/mnt/disk1
        - http://minio-2.minio-svc.default.svc.cluster.local/mnt/disk1
        - "--console-address=:9001"
          #- http://minio-3.minio.default.svc.cluster.local/mnt/disk1
          #- http://10.39.153.18:9090/
        ports:
        - name: api
          containerPort: 9000
          hostPort: 9000
          protocol: TCP
        - name: console
          containerPort: 9001
          hostPort: 9001
          protocol: TCP
        livenessProbe:
          exec:
            command: ["curl", "-f", "http://localhost:9000/minio/health/live"]
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 3
        readinessProbe:
          exec:
            command: ["curl", "-f", "http://localhost:9000/minio/health/live"]
          initialDelaySeconds: 3
          periodSeconds: 2
          timeoutSeconds: 1
        # These volume mounts are persistent. Each pod in the StatefulSet
        # gets a volume mounted based on this field.
        volumeMounts:
        - name: data
          mountPath: /mnt/disk1
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
      resources:
        requests:
          storage: 20Gi
